apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: csi-s3-storage
      persistentVolumeClaim:
        claimName: csi-s3-pvc
  containers:
    - name: task-pv-container
      image: nginx
      command: ["/bin/sh","-c"]
      args: ["touch /homework/file; printf Hello > /homework/file"]
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/homework"
          name:  csi-s3-storage
