apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-server
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app:  mysql
    spec:
      serviceAccountName: mysql
      containers:
      - name: mysql-operator
        image:  roflmaoinmysoul/mysql-operator:1.0.0
