apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: monitoring-global
subjects:
- kind: Group
  name: system:serviceaccounts:homework
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: monitoring-cr
  apiGroup: rbac.authorization.k8s.io
