kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
  namespace: homework
spec:
  storageClassName: deploy-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
