kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdbuild
  namespace: homework
subjects:
- kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  Role
  name:  rolecd
