apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  deploy-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: disk-csi-driver.mks.ycloud.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
