apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: app  # имя SecretStore
    kind: SecretStore
  target:
    name: otus-cred  # имя будущего секрета kubernetes
  data:
    - secretKey: username # ключ секрета
      remoteRef:
        key: otus/cred # путь до секрета в vault
        property: username # ключ секрета в vault
    - secretKey: password
      remoteRef:
        key: otus/cred
        property: password
