repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: kafka-prod
    namespace: prod
    chart: bitnami/kafka
    values:
      - kafka-prod-values.yaml

  - name: kafka-dev
    namespace: dev
    chart: bitnami/kafka
    values:
      - kafka-dev-values.yaml
